language: go
go:
 - tip

before_install:
 - sudo apt-get -qq update
 - sudo apt-get install -y libsdl2-dev
 - sudo apt-get install -y libsdl2-mixer-dev

install:
 - go get github.com/veandco/go-sdl2/sdl
 - go get github.com/veandco/go-sdl2/sdl_mixer

script:
 - go build ./...
