language: go

go:
    - 1.6
    # - tip

os:
    - linux
    - osx

notifications:
    email:
        on_success: never
        on_failure: always

branches:
    only:
        - master

install:
    - '[ "$TRAVIS_SECURE_ENV_VARS" == "false" ] || openssl aes-256-cbc -K $encrypted_2a6a96d3c45a_key -iv $encrypted_2a6a96d3c45a_iv -in tools/dropbox/.dropbox_uploader.enc -out ~/.dropbox_uploader -d'

    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update && brew tap andreas-jonsson/tap; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install -y rpl && export SDL_PREFIX=/usr/local && ./tools/sdl_from_source.sh; fi

script:
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install openwar; fi

    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then go get && go build openwar.go && go test -v ./...; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then ./tools/package/build_deb.sh && ./tools/dropbox/dropbox_uploader.sh upload openwar_0.0.1-$TRAVIS_BUILD_NUMBER.deb Public/openwar_0.0.1.deb; fi
