version: 0.0.1.{build}

platform: x64

branches:
    only:
        - master

clone_folder: c:\gopath\src\github.com\andreas-jonsson\openwar

environment:
    GOPATH: c:\gopath

install:
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.8.1.windows-amd64.msi
    - msiexec /i go1.8.1.windows-amd64.msi /q
    - go version
    - go env

    - 7z x %APPVEYOR_BUILD_FOLDER%\tools\build\dependencies.7z -o%APPVEYOR_BUILD_FOLDER%\tools\package
    - 7z x %APPVEYOR_BUILD_FOLDER%\tools\build\inno.7z -o"c:\Program Files (x86)"
    - 7z x %APPVEYOR_BUILD_FOLDER%\tools\build\TDM-GCC-64.7z -oc:\

    - set PATH="c:\Program Files (x86)\Inno Setup 5";"%GOPATH%\bin";c:\TDM-GCC-64\bin;%PATH%

build_script:
    - go get github.com/akavel/rsrc
    - rsrc -ico=tools/package/icon.ico -arch=amd64
    - go get -v
    - go build
    # - go build -ldflags="-H windowsgui"

after_build:
    # - iscc /Qp /O".\" /Fopenwar-%APPVEYOR_BUILD_VERSION%-win64 tools\package\setup.iss
    - iscc /Qp /O".\" tools\package\setup.iss

artifacts:
    # - path: openwar-%APPVEYOR_BUILD_VERSION%-win64.exe
    - path: openwar-0.0.1-win64.exe

deploy:
    # release: myproduct-v$(appveyor_build_version)
    description: 'Windows release'
    provider: GitHub
    auth_token:
        secure: tIlnLG7PbcjIDRCmagHNpJ8DdhKpZ9DBsHOypQJHO0ma5Nz3WWu6F4klCOuaNOSd
    artifact: openwar-0.0.1-win64.exe
    draft: false
    prerelease: true
    on:
        # branch: master
        appveyor_repo_tag: true
