version: 0.0.0.{build}

platform: x64

branches:
    only:
        - master

clone_folder: c:\gopath\src\github.com\andreas-jonsson\openwar

environment:
    GOPATH: c:\gopath

install:
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.3.windows-amd64.msi
    - msiexec /i go1.6.3.windows-amd64.msi /q
    - go version
    - go env
    
    # - curl -fsS -o setup.exe http://www.jrsoftware.org/download.php/ispack-unicode.exe
    # - setup.exe /SILENT
    
    - appveyor DownloadFile https://drive.google.com/open?id=0BwNOhD4ZlgzGMWg1dkMtZ0JUYms
    - 7zip.exe e -o c:\gopath\src\github.com\andreas-jonsson\openwar\tools\package\dependencies dependencies.7z
    
    - appveyor DownloadFile https://drive.google.com/open?id=0BwNOhD4ZlgzGaUx2VWp0VXlUalU
    - 7zip.exe e -o c:\TDM-GCC-64 TDM-GCC-64.7z

build_script:
    - go get
    - go build openwar.go
    - go test ./...
