version: 0.0.0.{build}

platform: x64

branches:
    only:
        - master

clone_folder: c:\gopath\src\github.com\andreas-jonsson\openwar

environment:
    GOPATH: c:\gopath

install:
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.3.windows-amd64.msi
    - msiexec /i go1.6.3.windows-amd64.msi /q
    - go version
    - go env
    
    # - curl -fsS -o setup.exe http://www.jrsoftware.org/download.php/ispack-unicode.exe
    # - setup.exe /SILENT

    - curl -L "https://drive.google.com/uc?export=download&confirm=aN6G&id=0BwNOhD4ZlgzGMWg1dkMtZ0JUYms" > dependencies.7z
    - 7z.exe x dependencies.7z -oc:\gopath\src\github.com\andreas-jonsson\openwar\tools\package\dependencies
    
    - curl -L "https://drive.google.com/uc?export=download&confirm=a0pc&id=0BwNOhD4ZlgzGaUx2VWp0VXlUalU" > TDM-GCC-64.7z
    - 7z.exe x TDM-GCC-64.7z -oc:\TDM-GCC-64

build_script:
    - go get
    - go build openwar.go
    - go test ./...
