version: 0.0.0.{build}

platform: x64

branches:
    only:
        - master

clone_folder: c:\gopath\src\github.com\andreas-jonsson\openwar

environment:
    GOPATH: c:\gopath

install:
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.3.windows-amd64.msi
    - msiexec /i go1.6.3.windows-amd64.msi /q
    - go version
    - go env

build_script:
    - go get
    - go build openwar.go
    - go test ./...
