version: 0.0.1.{build}

platform: x64

branches:
    only:
        - master

clone_folder: c:\gopath\src\github.com\andreas-jonsson\openwar

environment:
    GOPATH: c:\gopath

install:
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.3.windows-amd64.msi
    - msiexec /i go1.6.3.windows-amd64.msi /q
    - go version
    - go env

    - appveyor DownloadFile https://dl.dropboxusercontent.com/u/1955192/dependencies.7z
    - 7z e dependencies.7z -oc:\gopath\src\github.com\andreas-jonsson\openwar\tools\package -aoa

    - appveyor DownloadFile https://dl.dropboxusercontent.com/u/1955192/msys64.7z
    - del /F /S /Q c:\msys64
    - 7z e msys64.7z -oc:\ -aoa

build_script:
    - go get
    - echo /c/gopath/src/github.com/andreas-jonsson/openwar >> c:\msys64\home\phix\.bash_profile
    - echo go build openwar.go >> c:\msys64\home\phix\.bash_profile
    - echo exit >> c:\msys64\home\phix\.bash_profile
    - c:\msys64\mingw64_shell.bat

after_build:
    - 7z a openwar.zip openwar.exe tools\package\dependencies data

artifacts:
    - path: openwar-0.0.1.{build}-win64.zip
