version: 0.0.1.{build}

platform: x64

branches:
    only:
        - master

clone_folder: c:\gopath\src\github.com\andreas-jonsson\openwar

environment:
    GOPATH: c:\gopath

install:
    - appveyor DownloadFile https://storage.googleapis.com/golang/go1.6.3.windows-amd64.msi
    - msiexec /i go1.6.3.windows-amd64.msi /q
    - go version
    - go env

    - appveyor DownloadFile https://dl.dropboxusercontent.com/u/1955192/dependencies.7z
    - 7z x dependencies.7z -o%APPVEYOR_BUILD_FOLDER%\tools\package

    - appveyor DownloadFile https://dl.dropboxusercontent.com/u/1955192/inno.7z
    - 7z x inno.7z -o"c:\Program Files (x86)"

    - appveyor DownloadFile https://dl.dropboxusercontent.com/u/1955192/TDM-GCC-64.7z
    - 7z x TDM-GCC-64.7z -oc:\
    
    - set PATH="c:\Program Files (x86)\Inno Setup 5";c:\TDM-GCC-64\bin;%PATH%

build_script:
    - bash -c "go get && go build openwar.go"

after_build:
    # - iscc /Qp /O".\" /Fopenwar-%APPVEYOR_BUILD_VERSION%-win64 tools\package\setup.iss
    - iscc /Qp /O".\" tools\package\setup.iss

artifacts:
    # - path: openwar-%APPVEYOR_BUILD_VERSION%-win64.exe
    - path: openwar-0.0.1-win64.exe
