name: openwar
version: '0.0.1'
summary: 'OpenWar is an alternative Warcraft: Orcs & Humans game engine'
description: |
  OpenWar is an alternative Warcraft Orcs & Humans game engine.
  So unless you have a legal copy of Warcraft Orcs & Humans
  (original MS-DOS version required, won't work with the Mac or Demo versions)
  OpenWar will be pretty useless to you, since it doesn't come with
  any graphics or sounds itself.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  openwar:
    command: openwar

parts:
  openwar:
    plugin: dump
    source: ./snap
    organize:
      openwar: bin/openwar
